services:
  mongo:
    image: mongo:7.0.9
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoEcoexya
      - MONGO_INITDB_ROOT_PASSWORD=83pb9wM9F5fKxV
    networks:
      - mynetwork

  node-app:
    build: ./node-app
    container_name: node-app
    ports:
      - "3001:3001"
    volumes:
      - ./node-app:/app
    depends_on:
      - mongo
    environment:
      - MONGO_USERNAME=mongoEcoexya
      - MONGO_PASSWORD=83pb9wM9F5fKxV
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_DB=dbEcoexya
      - DEFAULT_ADMIN_USERNAME= admin@coexya.com
      - DEFAULT_ADMIN_PASSWORD= 321admin
      - MAIL_HOST=sandbox.smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USER=212b96f3519993
      - MAIL_PASSWORD=f7db70e15d24e7
    networks:
      - mynetwork

  react-app:
    build: ./react-app
    container_name: react-app
    ports:
      - "3000:3000" # Mappez le port 80 du conteneur (Nginx) au port 3000 de l'hôte
    volumes:
      - ./react-app:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo_data:
